name: mateusz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profil1.png
    - assets/images/profil2.png
    - assets/images/profil3.png
    - assets/images/profil4.png
    - assets/images/domek.png
    - assets/images/kupon.png
    - assets/images/logo.png
    - assets/images/Frantoio-Oil.png
    - assets/images/Juice.png
    - assets/images/Leccino-Oil.png
    - assets/images/left_arrow.png
    - assets/images/Margherita.png
    - assets/images/Penne all’arrabbiata.png
    - assets/images/Prosciutto e funghi.png
    - assets/images/Quattro Formaggi.png
    - assets/images/Spaghetti-Sicily.png
    - assets/images/Water.png
    - assets/images/Macaroni.png
  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Medium.ttf

    - family: MontSerrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
